# Generated by Django 5.0 on 2023-12-07 03:15

import django.db.models.deletion
import index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estados', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Estado de Garantía',
                'verbose_name_plural': 'Estados de Garantía',
                'db_table': 'EstadosGarantia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField(validators=[index.models.validate_fecha_vencimiento])),
                ('codigo_garantia', models.PositiveIntegerField(default=index.models.generate_codigo_garantia, unique=True)),
                ('detalles_garantia', models.CharField(max_length=100)),
                ('detalles_vehiculo', models.CharField(max_length=80)),
                ('estados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.estadosgarantia')),
            ],
            options={
                'verbose_name': 'Garantía',
                'verbose_name_plural': 'Garantías',
                'db_table': 'Garantia',
                'ordering': ['id'],
            },
        ),
    ]
