# Generated by Django 5.0 on 2024-02-01 23:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_cita_contacto_ocupacion_tipodeservicio_comentario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField(default=django.utils.timezone.now)),
                ('monto_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detalles_venta', models.TextField()),
                ('garantia_relacionada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.garantia')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'Ventas',
                'ordering': ['id'],
            },
        ),
    ]
